export enum LINKS {
  HOME = "/",
  CATALOG = "/products?category=undefined",
  CATALOG_BICYCLE = "/products?category=bicycle",
  CATALOG_ACCESSORY = "/products?category=accessory",
  CATALOG_GYROBOARD = "/products?category=gyroboard",
  CATALOG_MONOWHEEL = "/products?category=monowheel",
  CATALOG_SCOOTER = "/products?category=scooter",
  CATALOG_SKATEBOARD = "/products?category=skateboard",
  CART = "/profile/cart",
  ARCHIVE = "/profile/archive",
  FAVORITES = "/profile/favorites",
  PROFILE = "/profile",
  ORDERS = "/profile/orders",
  SETTINGS = "/profile/settings",
  SEARCH = "/search",
}
