export const products = [
  {
    id: 1,
    characteristic:
      "speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm",
    rating: 4.45,
    inStock: true,
    price: 120,
    discription:
      "Voluptate aliquip pariatur occaecat adipisicing commodo sit id ut elit est. Ad minim sit reprehenderit ea excepteur. Sit reprehenderit elit ut do occaecat fugiat cillum irure excepteur duis. Minim duis esse exercitation culpa do in. Deserunt minim sunt fugiat magna ad proident dolor. Cupidatat consequat consectetur sit commodo id amet nostrud adipisicing dolore. Cillum amet aliqua consectetur laborum sint aliquip laboris do do excepteur excepteur enim adipisicing. Labore fugiat sunt ut laboris dolor culpa. Esse aliqua consequat pariatur fugiat id deserunt eiusmod ea irure. Anim esse proident labore dolor enim dolor elit enim excepteur nostrud duis Lorem amet incididunt. Incididunt anim velit minim pariatur exercitation ut occaecat quis Duis qui adipisicing occaecat amet quis aliqua proident aliqua tempor in officia. Laboris mollit est reprehenderit in. Magna sint laboris eiusmod dolore pariatur pariatur pariatur. Veniam ea est do sint eu non. Reprehenderit consectetur Lorem do laborum. Non nostrud amet ex deserunt consequat non veniam deserunt id velit dolor. Labore labore excepteur irure ullamco laboris ea anim. Non laborum sint pariatur do ut consectetur cillum quis exercitation ad incididunt incididunt enim culpa. Officia tempor adipisicing in irure aliquip eu aute id irure.",
    name: "GLB 200 AMG Line Executive 7G-DCT",
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      {
        id: 1,
        name: "string",
        url: "https://picsum.photos/1280/720",
        articleId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    sale: {
      id: 1,
      newPrise: 100,
      activeTill: new Date(),
      articleId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: 2,
    characteristic:
      "speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm",
    rating: 4.45,
    inStock: false,
    price: 120,
    discription: "Very cool product for you",
    name: "GLB 200 AMG Line Executive 7G-DCT",
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    sale: {
      id: 1,
      newPrise: 100,
      activeTill: new Date(),
      articleId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },

  {
    id: 3,
    characteristic:
      "speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm",
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: "Very cool product for you",
    name: "GLB 200 AMG Line Executive 7G-DCT",
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    characteristic:
      "speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm",
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: "Very cool product for you",
    name: "GLB 200 AMG Line Executive 7G-DCT",
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    characteristic:
      "speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm",
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: "Very cool product for you",
    name: "GLB 200 AMG Line Executive 7G-DCT",
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    characteristic:
      "speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm",
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: "Very cool product for you",
    name: "GLB 200 AMG Line Executive 7G-DCT",
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    characteristic:
      "speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm",
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: "Very cool product for you",
    name: "GLB 200 AMG Line Executive 7G-DCT",
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
