export const products = [
  {
    id: 1,
    characteristic:
      'speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm',
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: 'Very cool product for you',
    name: 'GLB 200 AMG Line Executive 7G-DCT',
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      {
        id: 1,
        name: 'string',
        url: 'https://europe.starconnect-ce.i.mercedes-benz.com/iris/iris.jpg?COSY-EU-100-1713d0VXqNEFqtyO67PobzIr3eWsrrCsdRRzwQZYZ4ZbMw3SGtle9tsd2HVcUfpOcXGEunSJ0l3ofOB2qBqbApRTyI5uGoxQC30SpkzNHTwm7j86jhKViKw%25vq4c9yLRhcVYax%255SrH1GBln8w0zEoiZB%25YM4FAOFTg9LQ36PDacpSeWHXRtsd8otcUfiM1XGE4JYJ0lgCVOB2PzFbApeYlI5ulmJQC32S1kzNL6Sm%25kbFDZk3tsdHZTcUfarRXGE1VSevHWqtsc%25NRcUXyJxXGJYs1J0Ou2wOBbeRZbM8rGRWvzHF8Q4oGAIApF5BUkk74WgCV5g9jP4HtHpBp%250oThUy0QKkcYn6M8zpCSlnO3pSR4Zw=&BKGND=9&POV=BE040,PZM,SZD&uni=c&fb=1&width=1280&height=720&IMGT=W27',
        articleId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    sale: {
      id: 1,
      newPrise: 100,
      activeTill: new Date(),
      articleId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: 2,
    characteristic:
      'speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm',
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: 'Very cool product for you',
    name: 'GLB 200 AMG Line Executive 7G-DCT',
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 3,
    characteristic:
      'speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm',
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: 'Very cool product for you',
    name: 'GLB 200 AMG Line Executive 7G-DCT',
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    characteristic:
      'speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm',
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: 'Very cool product for you',
    name: 'GLB 200 AMG Line Executive 7G-DCT',
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    characteristic:
      'speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm',
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: 'Very cool product for you',
    name: 'GLB 200 AMG Line Executive 7G-DCT',
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    characteristic:
      'speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm',
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: 'Very cool product for you',
    name: 'GLB 200 AMG Line Executive 7G-DCT',
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    characteristic:
      'speed: 100 km/h; color: red; weight: 100 kg; size: 100x100x100 cm',
    rating: 4.45,
    inStock: true,
    price: 120,
    discription: 'Very cool product for you',
    name: 'GLB 200 AMG Line Executive 7G-DCT',
    count: 1,
    views: 1,
    isPreviouslyUsed: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
